export const GET_RECIPES = "GET RECIPES";
export const ADD_RECIPES = "ADD RECIPES";
export const ADD_RECIPES_START = "ADD RECIPES START";
export const ADD_RECIPES_SUCCESS = "ADD RECIPES SUCCESS";
export const DELETE_RECIPES = "DELETE RECIPES";
export const GET_RECIPES_SUCCESS = "GET RECIPES SUCCESS";
export const LOADING = "LOADING";
export const ERROR_OCCURED = "ERROR_OCCURED";